(() => {
'use strict';
const $=id=>document.getElementById(id),root=document.documentElement;
const projects=window.PORTFOLIO_PROJECTS||[];
const write=(key,value)=>{try{localStorage.setItem(key,value);return true;}catch{return false;}};
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const motionQuery=matchMedia('(prefers-reduced-motion: reduce)');
let manualPause=false;
try{manualPause=localStorage.getItem('portfolio-motion')==='reduced';}catch{}
let toastTimer;
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3200);}
function syncMotion(){const paused=manualPause||motionQuery.matches;root.dataset.motion=paused?'paused':'full';$('motion-toggle').textContent=paused?'Motion paused ▷':'Pause motion Ⅱ';$('motion-toggle').setAttribute('aria-pressed',String(paused));$('motion-toggle').disabled=motionQuery.matches;$('motion-toggle').title=motionQuery.matches?'Reduced motion is enabled in your system settings':'';$('motion-metric').textContent=paused?'Reduced':'Enabled';}
$('motion-toggle').addEventListener('click',()=>{manualPause=!manualPause;write('portfolio-motion',manualPause?'reduced':'full');syncMotion();});
motionQuery.addEventListener('change',syncMotion);syncMotion();
function syncTheme(){const light=root.dataset.theme==='light';$('theme-toggle').setAttribute('aria-pressed',String(light));$('theme-toggle').setAttribute('aria-label',light?'Use dark theme':'Use light theme');document.querySelector('meta[name="theme-color"]').content=light?'#f2f2e9':'#10120f';}
$('theme-toggle').addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='light'?'dark':'light';write('portfolio-theme',root.dataset.theme);syncTheme();});syncTheme();
document.addEventListener('visibilitychange',()=>root.classList.toggle('page-hidden',document.hidden));
// Navigation preserves real URLs and works without JavaScript.
const nav=$('primary-nav');
function closeMenu(){nav.classList.remove('is-open');$('menu-toggle').setAttribute('aria-expanded','false');$('menu-toggle').setAttribute('aria-label','Open navigation');}
$('menu-toggle').addEventListener('click',()=>{const open=nav.classList.toggle('is-open');$('menu-toggle').setAttribute('aria-expanded',String(open));$('menu-toggle').setAttribute('aria-label',open?'Close navigation':'Open navigation');});
nav.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu();});
document.addEventListener('click',e=>{if(!e.target.closest('.top'))closeMenu();});
document.querySelector('.top').addEventListener('focusout',e=>{if(e.relatedTarget&&!e.currentTarget.contains(e.relatedTarget))closeMenu();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('is-open')){closeMenu();$('menu-toggle').focus();}});
function go(id,record=true){const target=$(id);if(!target)return;if(target.tagName==='DETAILS')target.open=true;if(record&&location.hash!=='#'+id)history.pushState(null,'','#'+id);target.tabIndex=-1;target.focus({preventScroll:true});target.scrollIntoView({behavior:root.dataset.motion==='paused'?'instant':'smooth',block:'start'});}
function route(){let id;try{id=decodeURIComponent(location.hash.slice(1));}catch{return;}const aliases={'/projects':'notebook',projects:'work','/':'home',path:'skills'};go(aliases[id]||id,false);}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a||e.defaultPrevented||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;const id=a.getAttribute('href').slice(1);if(!$(id))return;e.preventDefault();go(id);});
window.addEventListener('hashchange',route);route();
let scrollFrame=0;
const sectionIds=['work','lab','about','contact'];
function updateScroll(){scrollFrame=0;const max=document.documentElement.scrollHeight-innerHeight;const percent=max>0?Math.min(1,Math.max(0,scrollY/max)):0;$('scroll-progress').style.transform=`scaleX(${percent})`;let active='';sectionIds.forEach(id=>{if($(id).getBoundingClientRect().top<180)active=id;});if(percent>.995&&scrollY>0)active='contact';nav.querySelectorAll('a').forEach(a=>{if(a.hash==='#'+active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}
function scheduleScroll(){if(!scrollFrame)scrollFrame=requestAnimationFrame(updateScroll);}
window.addEventListener('scroll',scheduleScroll,{passive:true});window.addEventListener('resize',scheduleScroll,{passive:true});if('ResizeObserver'in window)new ResizeObserver(scheduleScroll).observe(document.body);scheduleScroll();
// Persist only validated IDs. Broken or blocked storage never prevents browsing.
const SAVED_KEY='mf-saved-projects-v2';let saved=new Set(),storageWritable=true;
try{const raw=localStorage.getItem(SAVED_KEY);if(raw){const items=JSON.parse(raw);if(!Array.isArray(items))throw Error();saved=new Set(items.filter(id=>projects.some(p=>p.id===id)));}}catch{storageWritable=false;}
function saveSelection(){if(storageWritable&&!write(SAVED_KEY,JSON.stringify([...saved])))storageWritable=false;}
function updateSaved(){document.querySelectorAll('[data-save]').forEach(b=>{const yes=saved.has(b.dataset.save),p=projects.find(p=>p.id===b.dataset.save);b.setAttribute('aria-pressed',String(yes));b.setAttribute('aria-label',(yes?'Unsave ':'Save ')+(p?.title||'project'));b.textContent=b.classList.contains('bookmark')?(yes?'◆':'◇'):(yes?'Saved to your shortlist ✓':'Save this project ◇');});$('saved-count').textContent=saved.size;}
let category='all';const cards=[...document.querySelectorAll('.project-card')];
function filter(){const q=$('project-search').value.trim().toLowerCase();let count=0;cards.forEach(card=>{const p=projects.find(p=>p.id===card.dataset.project);const matches=(category==='all'||(category==='saved'?saved.has(p.id):p.category===category))&&[p.title,p.summary,...p.tags,...p.bullets].join(' ').toLowerCase().includes(q);card.hidden=!matches;if(matches)count++;});$('project-count').textContent=`${count} of ${cards.length} projects${category==='saved'?' saved':''}${q?' matching your search':''}`;$('project-empty').hidden=count!==0;scheduleScroll();}
function setFilter(value){category=value;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===category)));filter();}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));
$('project-search').addEventListener('input',filter);$('reset-filters').addEventListener('click',()=>{$('project-search').value='';setFilter('all');$('project-search').focus();});
$('view-toggle').addEventListener('click',()=>{const list=$('project-grid').classList.toggle('list-view');$('view-toggle').setAttribute('aria-pressed',String(list));$('view-toggle').textContent=list?'Grid view ▦':'List view ☷';});
document.querySelectorAll('[data-tech]').forEach(b=>b.addEventListener('click',e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();$('project-search').value=b.dataset.tech;setFilter('all');go('work');}));
document.addEventListener('click',e=>{const b=e.target.closest('[data-save]');if(!b)return;const id=b.dataset.save;if(!projects.some(p=>p.id===id))return;const yes=!saved.has(id);yes?saved.add(id):saved.delete(id);saveSelection();updateSaved();filter();toast((yes?'Project saved.':'Project removed from saved.')+(!storageWritable?' Kept for this visit only.':''));if(b.hidden||!b.getClientRects().length)document.querySelector('[data-filter="saved"]').focus();});
window.addEventListener('storage',e=>{if(e.key!==SAVED_KEY&&e.key!==null)return;try{const values=e.newValue?JSON.parse(e.newValue):[];if(!Array.isArray(values))return;saved=new Set(values.filter(id=>projects.some(p=>p.id===id)));updateSaved();filter();}catch{}});
updateSaved();filter();
// Native dialogs give keyboard users consistent Escape and focus behavior.
const openers=new WeakMap();
function openDialog(dialog){document.querySelectorAll('dialog[open]').forEach(d=>d.close());openers.set(dialog,document.activeElement);closeMenu();dialog.showModal();}
function closeDialog(dialog){dialog.close();}
document.querySelectorAll('dialog').forEach(dialog=>{dialog.addEventListener('close',()=>{const opener=openers.get(dialog);if(document.querySelector('dialog[open]'))return;const active=document.activeElement;if(active!==document.body&&!dialog.contains(active))return;if(opener?.isConnected&&opener.getClientRects().length)opener.focus({preventScroll:true});else (document.querySelector('[data-filter="'+category+'"]')||$('command-open')).focus();});dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const box=dialog.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)dialog.close();});dialog.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const items=[...dialog.querySelectorAll('a[href],button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]')].filter(n=>n.getClientRects().length);if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});});
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeDialog($(b.dataset.close))));
function openProject(id){const p=projects.find(p=>p.id===id);if(!p)return;const host=$('case-content');host.replaceChildren();$('case-context').textContent=p.index+' / '+p.context;const h=el('h2',p.title);h.id='project-dialog-title';host.append(h,el('p',p.summary,'case-summary'));const tags=el('div',undefined,'tags');p.tags.forEach(t=>tags.append(el('span',t,'tag')));host.append(tags,el('p',p.role,'case-role'));const notes=el('div',undefined,'case-notes');notes.append(el('h3','What I worked on'));const ul=el('ul');p.bullets.forEach(t=>ul.append(el('li',t)));notes.append(ul);host.append(notes,el('p',p.takeaway,'case-takeaway'));const actions=el('div',undefined,'case-actions');const save=el('button','Save this project ◇','btn');save.dataset.save=p.id;save.type='button';actions.append(save);if(p.id==='flask'){const button=el('button','Try the request playground ↗','btn primary');button.addEventListener('click',()=>{closeDialog($('project-dialog'));go('lab');});actions.append(button);}const gh=el('a','My GitHub profile ↗','text-link');gh.href='https://github.com/maxfona20';gh.target='_blank';gh.rel='noopener noreferrer';gh.setAttribute('aria-label','My GitHub profile (new tab)');actions.append(gh);host.append(actions);if(p.id==='venmo'&&window.initPortfolioWallet){const wallet=el('div');wallet.dataset.wallet='';host.append(wallet);window.initPortfolioWallet(wallet);}if(p.id==='ai'){const process=el('div',undefined,'production-flow');process.append(el('p','THE CONTENT WORKFLOW','eyebrow'));const ol=el('ol');['Script & plan','Generate visuals','Create voice','Edit & publish'].forEach((v,i)=>{const li=el('li');li.append(el('span',String(i+1).padStart(2,'0'),'mono'),el('strong',v));ol.append(li);});process.append(ol);host.append(process);}updateSaved();openDialog($('project-dialog'));$('project-dialog').scrollTop=0;}
document.querySelectorAll('[data-case]').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.case)));
// Command menu can search project names as well as sections and actions.
const commands=[{label:'Selected work',hint:'SECTION',run:()=>go('work')},{label:'Request playground',hint:'TRY IT',run:()=>go('lab')},{label:'About Max',hint:'SECTION',run:()=>go('about')},{label:'Experience',hint:'SECTION',run:()=>go('experience')},{label:'Skills & certifications',hint:'SECTION',run:()=>go('skills')},{label:'Contact',hint:'SECTION',run:()=>go('contact')},{label:'Download résumé',hint:'PDF',run:()=>document.querySelector('.hero a[download]').click()},{label:'Saved projects',hint:'SHORTLIST',run:()=>{$('project-search').value='';setFilter('saved');go('work');}},{label:'Switch color theme',hint:'APPEARANCE',run:()=>$('theme-toggle').click()},{label:'Pause or resume motion',hint:'PREFERENCE',run:()=>$('motion-toggle').click()},{label:'Local project notebook',hint:'LOCAL DEMO',run:()=>go('notebook')},{label:'Surprise me',hint:'RANDOM PROJECT',run:()=>openProject(projects[Math.floor(Math.random()*projects.length)].id)},...projects.map(p=>({label:p.title,hint:'PROJECT',run:()=>openProject(p.id)}))];
function renderCommands(){const q=$('command-input').value.trim().toLowerCase();$('command-list').replaceChildren();commands.filter(c=>c.label.toLowerCase().includes(q)&&!(c.hint==='PREFERENCE'&&motionQuery.matches)).forEach(c=>{const li=el('li'),b=el('button');b.type='button';b.append(el('span',c.label),el('small',c.hint));b.addEventListener('click',()=>{closeDialog($('command-dialog'));c.run();});li.append(b);$('command-list').append(li);});$('command-empty').hidden=$('command-list').children.length>0;}
function openCommands(){if($('command-dialog').open){closeDialog($('command-dialog'));return;}$('command-input').value='';renderCommands();openDialog($('command-dialog'));$('command-input').focus();}
$('command-open').addEventListener('click',openCommands);$('command-input').addEventListener('input',renderCommands);
$('command-dialog').addEventListener('keydown',e=>{const buttons=[...$('command-list').querySelectorAll('button')];if(!buttons.length)return;const index=buttons.indexOf(document.activeElement);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const next=e.key==='ArrowDown'?(index+1)%buttons.length:(index<=0?buttons.length-1:index-1);buttons[next].focus();}if(e.key==='Enter'&&document.activeElement===$('command-input')){e.preventDefault();buttons[0].click();}});
document.addEventListener('keydown',e=>{const typing=e.target.closest('input,textarea,select,[contenteditable="true"]');if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommands();}else if(e.key==='/'&&!typing&&!e.metaKey&&!e.ctrlKey&&!e.altKey&&!document.querySelector('dialog[open]')){e.preventDefault();openCommands();}});
$('copy-email').addEventListener('click',async()=>{try{if(!navigator.clipboard)throw Error();await navigator.clipboard.writeText('maxfona20@gmail.com');$('copy-status').textContent='Email copied. Let’s talk.';}catch{$('copy-status').textContent='Copy this address: maxfona20@gmail.com';}});
// CLS is observed, never fabricated; unsupported browsers show an honest fallback.
if('PerformanceObserver'in window&&PerformanceObserver.supportedEntryTypes?.includes('layout-shift')){let cls=0;new PerformanceObserver(list=>{for(const e of list.getEntries())if(!e.hadRecentInput)cls+=e.value;$('cls-metric').textContent=cls.toFixed(3);}).observe({type:'layout-shift',buffered:true});$('cls-metric').textContent='0.000';}else $('cls-metric').textContent='Unavailable';
})();
